### ISSUE TITLE
METplus use case failures from METdataio

### ISSUE THREAD

**Issue by venitahagerty** [dtcenter/METdatadb#204]
## Describe the Problem ##
Reported by George:

COPYABLE ENVIRONMENT FOR NEXT COMMAND:
export METPLOTPY_BASE="/metplus/METplus/../METplotpy"; export MET_TMP_DIR="/data/output/met_tool_wrapper/METdbLoad/tmp"; export OMP_NUM_THREADS="1";

COMMAND:
python3 /metplus/METplus/../METdataio/METdbLoad/ush/met_db_load.py /data/output/met_tool_wrapper/METdbLoad/tmp/metplus_tmp_JQmnQixJxs

OUTPUT:
INFO:root:METdbload Version: __version__ = "2.1.0-rc1-dev"
INFO:root:--- *** --- Start METdbLoad --- *** ---
INFO:root:Begin time: 2023-05-04 20:07:32.838358
INFO:root:User name is: root
INFO:root:Reading XML Load file
Traceback (most recent call last):
  File "/metplus/METplus/../METdataio/METdbLoad/ush/met_db_load.py", line 408, in <module>
    main()
  File "/metplus/METplus/../METdataio/METdbLoad/ush/met_db_load.py", line 88, in main
    xml_loadfile.read_xml()
  File "/metplus/METdataio/METdbLoad/ush/read_load_xml.py", line 96, in read_xml
    self.read_db_connect(root)
  File "/metplus/METdataio/METdbLoad/ush/read_load_xml.py", line 246, in read_db_connect
    root.xpath('connection')[0].xpath('management_system')[0].text
IndexError: list index out of range

### Expected Behavior ###
It looks like there are some missing tags in the XML file, but met_db_load.py should handle them better than this and give a good error message.

### Environment ###
Describe your runtime environment:
*1. Machine: Mac Laptop*
*2. OS: MacOS*
*3. Monterey 12.5, Python 3.10*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*Will add METplus to GitHub Actions checks*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
@georgemccabe @TatianaBurek @bikegeek @fisherhucar I'm not sure if this is how it's supposed to be done, but George found a bug in met_db_load.py. He asked me to include a new GitHub Action file (Trigger METplus Workflow) that runs METplus but only runs when pushed to develop. So I fixed the bug, added the  GitHub Action file, and created and merged Pull Request 205.

Successful output is here:
https://github.com/dtcenter/METdataio/actions/runs/4894164580

**Comment by georgemccabe** [comment]
Thanks for fixing the bug and adding the workflow to trigger METplus. I see the METplus workflow was triggered properly and successed after the bugfix. https://github.com/dtcenter/METplus/actions/runs/4894166278
