### ISSUE TITLE
Update database to load 7 new MODE CTS statistics

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#226]
## Describe the Enhancement ##
MET issue dtcenter/MET#2648 and corresponding pull request dtcenter/MET#2655 adds 7 new columns of output to the end of the MODE CTS line type:
   LODDS, ORSS, EDS, SEDS, EDI, SEDI, BAGSS
 
This issue is to update METdataio to load this new data.  Include instructions in the Release Notes and provide an update_for_v_x_release_cycle.sql in the METdataio/METdbLoad/sql/udates directory

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues

Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Possibly done, find original pull request to link

**Comment by bikegeek** [comment]
Looking at the METdbLoad/ush/constants.py, these 7 columns are included, so data containing these columns will be loaded.  These columns are also present in the METdbLoad/sql/mv_mysql.sql file.  **However, these columns need to be added to the METdbLoad/sql/updates/update_for_6_0_beta6.sql since this hasn't been included in previous _update_for_x_y_<dev-release>.sql file_s**

**Comment by bikegeek** [comment]
It appears that the update_x_y_<cycle>.sql is not needed, upon looking at a recently created database, these 7 columns and their corresponding bootstrap columns are already present.

Closing this issue as already completed.
