### ISSUE TITLE
Bugfix METdataio isn't correctly placing the database in the correct METviewer group

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METdatadb#228]
## Describe the Problem ##
Tina has found that when explicitly setting the group to RAL Projects in the XML specification file, the database is loaded in the METviewer mariaDB database, but is placed in the incorrect group.

### Expected Behavior ###
on 'mohawk', using the following script to set up the METviewer database (MAKE MODIFICATIONS TO CREATE A _DIFFERENT_ DATABASE):

```
#!/bin/sh -v
 
 dbname="mv_debugging"
 #host="mohawk"
 host="localhost"
 #metv="/d2/projects/METViewer/src/apps/METviewer"
 metv="/d2/personal/mwin/Debug_METdataio_for_METviewer/METdataio/METdbLoad"
 #path2proj="/d2/projects/UAE_tk/metv"
 path2proj="/d2/personal/mwin/Debug_METdataio_for_METviewer/METdataio/METdbLoad/sql"
 mvuser="mvuser"
 #mvuser="mvadmin"
 mvpass="mvuser"
 #mvpass="160GiltVa0D5M"

 # Drop the database before creating
 mysql -h${host} -u${mvuser} -p${mvpass} -e"drop database ${dbname};"
 mysql -h${host} -u${mvuser} -p${mvpass} -e"create database ${dbname};"
 mysql -h${host} -u${mvuser} -p${mvpass} ${dbname} < ${metv}/sql/mv_mysql.sql
 ${metv}/bin/mv_load.sh ${path2proj}/load_${dbname}.xml > ${path2proj}/load_${dbname}.log 2>&1


```

Next, use the following specification file (MAKE MODIFICATIONS TO MATCH THE DATABASE CREATED ABOVE and point to the correct paths for the schema):

```
<load_spec>
	<connection>
		<host>mohawk</host>
		<database>mv_uae_2022_upa</database>
		<user>mvuser</user>
		<password>mvuser</password>
	</connection>

        <date_list name="folder_dates">
        <start>2023010100</start>
        <end>2023073018</end>
        <inc>21600</inc>
        <format>yyyyMMddHH</format>
        </date_list>

	<folder_tmpl>/d2/projects/UAE_tk/data/{datadir}/{ltype}/{date}</folder_tmpl>


	<verbose>true</verbose>
	<insert_size>1</insert_size>
	<stat_header_db_check>true</stat_header_db_check>
	<mode_header_db_check>true</mode_header_db_check>
	<drop_indexes>false</drop_indexes>
	<apply_indexes>true</apply_indexes>
	<load_stat>true</load_stat>
	<load_mode>false</load_mode>
	<load_mpr>true</load_mpr>
	<group>RAL Projects</group>

	<load_val>
		<field name="datadir">
			<val>EnVar_G1V_stats</val>
                        <val>EnVar_G2V_stats</val>
		</field>
                <field name="ltype">
                        <val>point_stat_ua</val>
                </field>
                <field name="date">
			<date_list name="folder_dates"/>
                </field>
	</load_val>

	<load_xml>true</load_xml>
</load_spec>
```

Verify that the new database you created above is **NOT** in the _RAL Projects_ group via METviewer:
http://dtcenter.ucar.edu/met/metviewer/metviewer1.jsp

by looking under the _RAL Projects_ group for the database you created.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)**  required
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x]Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
loading code expects both tags to be present <group> and <description>. Only in this case 'group' data is loaded into the database.
In reality, <description> is optional. Need to change the code to load <group> even the <description> is missing

**Comment by TatianaBurek** [comment]
The initial value of self.description is 'None'. it should be an empty sting.
The logic for inserting group and description also needs to be fixed also
