### ISSUE TITLE
Error loading ECLV(ECON) line type from VSDB files

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METdatadb#32]
[mv_dev.txt](https://github.com/NCAR/METdb/files/5008653/mv_dev.txt)

*Lines with ECLV(ECON) line type from VSDB files are not in eclv tables.
Count comparison:
line_data_eclv        1339    83
line_data_eclv_pnt 24165  1557
File for testing:
met_data/ens_vsdb/2011070100/sref/sref_20141004.vsdb
line #1101*

### Expected Behavior ###
*Both databases should have the same count*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. run query on both databases: 
`select * from line_data_eclv, line_data_eclv_pnt, data_file  where line_data_eclv.line_num=1101 and line_data_eclv.data_file_id=data_file.data_file_id and data_file.filename="sref_20141004.vsdb" and line_data_eclv.line_data_id=line_data_eclv_pnt.line_data_id`*
*2. The result should be similar to the data from the attached file*

*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
This error was caused by having NA values in fcst_lead and obs_lead, which had not been seen before. Added code to convert these NA values to 0.

This revealed the issue that when there is an error in a batch of files, none of the files in that batch are loaded into the database. This is a more complicated issue to solve. Will add another issue for that.
