### ISSUE TITLE
Create initial METdbload documentation

### ISSUE THREAD

**Issue by venitahagerty** [dtcenter/METdatadb#46]
*Create initial METdbload documentation*

## Describe the New Feature ##
*Create .rst files for documentation, based on MVLoad documentation.*

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*3 days of work*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
Created initial documentation based on the METviewer MVLoad documentation.

**Comment by TatianaBurek** [comment]
Venita
I looked at .rst files in METdbLoad/docks and here are my comments:
- move docs one level up under METdatadb and put it under new directory Users_Guide like in other repos
- installation.rst;
      - add MariaDB line 20
      - add cloning from GitHub line 27
      - remove development instructions line 58 ( docs are for the general public)
      - remove 'Making a Database Accessible...' line 68 - this would go to METviewer docs
- overview.rst: 
      - add MariaDB line 32
      - not sure about the DTC section since this is a general guide not just for DTC

**Comment by venitahagerty** [comment]
I made most of the changes.

I've written this as a METdbload User's Guide. It's the only part of METdatadb created so far. It seems more logical to me to wait to make this a METdatadb User's Guide until after more components (like remove duplicates or change variable names) are added.

**Comment by venitahagerty** [comment]
Julie is moving the documentation up under METdatadb as part of issue 47.
